### ISSUE TITLE
check-ospf-neighbor-state iAgent table name need to be modified

### ISSUE THREAD

**Issue by d200201123** [Juniper/healthbot-rules#197]
Rule “check-ospf-neighbor-information” and “check-ospf-neighbor-state” in “protocol.ospf”  are using the same iAgent table name but from different yaml files.

Due to this if the both rules are deployed in same device-group data generated is not proper.

Modify one of the rule to have a different table name

#### ospf.yml
```
OspfNeighborTable:
  rpc: get-ospf-neighbor-information
  args:
    extensive: !!bool True
  item: ospf-neighbor
  key:
    - interface-name
    - neighbor-id
  view: OspfNeighborView

OspfNeighborView:
  fields:
    ospf-neighbor-state: ospf-neighbor-state
    activity-timer: activity-timer
    neighbor-up-time: neighbor-up-time
    neighbor-adjacency-time: neighbor-adjacency-time
```

#### ospf-neighbor.yml
```
OspfNeighborTable:
    command: show ospf neighbor
    key: Address
    view: OspfNeighborView
OspfNeighborView:
    columns:
        neighbor_address: Address
        interface: Interface
        neighbor_state: State
        neighbor_id: ID
        neighbor_priority: Pri
        activity_timer: Dead
```
